# Generated by Django 3.2.8 on 2022-01-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220106_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopes',
            options={'ordering': ['-is_main', 'tag']},
        ),
        migrations.RenameField(
            model_name='scopes',
            old_name='category',
            new_name='tag',
        ),
    ]
