# Generated by Django 3.2.8 on 2022-01-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220107_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopes',
            options={'ordering': ['-is_main', 'category']},
        ),
        migrations.RenameField(
            model_name='scopes',
            old_name='tag',
            new_name='category',
        ),
    ]
