# Generated by Django 3.2.8 on 2022-01-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_scopes_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopes',
            options={'ordering': ['-is_main', 'tag']},
        ),
        migrations.RenameField(
            model_name='scopes',
            old_name='category',
            new_name='tag',
        ),
    ]
